"""empty message

Revision ID: 37aa97008a11
Revises: 
Create Date: 2024-03-05 11:01:11.498295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37aa97008a11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=9), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('Url_imagen', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('doctores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=9), nullable=False),
    sa.Column('id_Especialidad', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('Url_imagen', sa.String(length=500), nullable=True),
    sa.Column('url_Calendly', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_Especialidad'], ['especialidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_Usuario', sa.Integer(), nullable=True),
    sa.Column('id_Doctor', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.String(length=150), nullable=False),
    sa.Column('Hora', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['id_Doctor'], ['doctores.id'], ),
    sa.ForeignKeyConstraint(['id_Usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    op.drop_table('doctores')
    op.drop_table('usuarios')
    op.drop_table('user')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
