"""empty message

Revision ID: 88e0e16a3c71
Revises: ba099e7eff1c
Create Date: 2024-02-26 20:06:39.679142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e0e16a3c71'
down_revision = 'ba099e7eff1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_Calendly', sa.String(length=150), nullable=True))
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_column('url_Calendly')

    # ### end Alembic commands ###
