"""empty message

Revision ID: 96f6eb62932d
Revises: a73a781c9dcb
Create Date: 2024-02-26 18:15:30.486023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f6eb62932d'
down_revision = 'a73a781c9dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactanos', schema=None) as batch_op:
        batch_op.drop_constraint('contactanos_id_user_fkey', type_='foreignkey')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactanos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('contactanos_id_user_fkey', 'user', ['id_user'], ['id'])

    # ### end Alembic commands ###
