"""empty message

Revision ID: a925c0b74a45
Revises: 88e0e16a3c71
Create Date: 2024-02-26 20:27:31.479631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a925c0b74a45'
down_revision = '88e0e16a3c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctores', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
